### ISSUE TITLE
Folder vendor

### ISSUE THREAD

**Issue by KNobHack** [abdilah21/app_osis#1]
Folderna gede teuing dan.

mending di hapus wae, terus tambahan .gitignore.
kakadi download lewat composer masing masing wae.

_Pull request na OTW._

**Comment by dadanabdilah** [comment]
Ngahapusna kumha kang
Pada tanggal 26 Apr 2020 18:49, "KNobHack" <notifications@github.com>
menulis:

**Comment by KNobHack** [comment]
Aya di Pull request urang dan, tinggal di acc wae 👍
